---
# tasks file for snipeclone_enableit
 
   - name: Permission 1
     shell: sudo chown -R www-data:www-data /var/www/snipeit/

   - name: Permission 2
     shell: sudo chmod -R 755 /var/www/snipeit/

   -  name: replace .env
      copy:
        src: .env
        dest: /var/www/snipeit/.env

   -  name: replace snipeit.conf
      copy:
        src: snipeit.conf
        dest: /etc/apache2/sites-available/snipeit.conf

   - name: Generating Key
     shell: sudo php artisan key:generate --force
     args:
       chdir: /var/www/snipeit/

   - name: Generating Key
     shell: sudo a2enmod rewrite
     args:
       chdir: /etc/apache2/sites-available/

   - name: Ensite
     shell: sudo a2ensite snipeit.conf
     args:
       chdir: /etc/apache2/sites-available/

   - name: Dissite
     shell: sudo a2dissite 000-default.conf
     args:
       chdir: /etc/apache2/sites-available/
     notify:
        - Restart apache

